// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjGVHy5QKMbkLMtmySwNfImbhMhlPDLWg',
    appId: '1:554785606851:web:d5852312ece1db7f9d6676',
    messagingSenderId: '554785606851',
    projectId: 'movie-app-d9b1d',
    authDomain: 'movie-app-d9b1d.firebaseapp.com',
    storageBucket: 'movie-app-d9b1d.appspot.com',
    measurementId: 'G-ZHCW5TWMR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1EStMi-J676hVyrhsQusSrTDiKbGdUHk',
    appId: '1:554785606851:android:3926356346febd4a9d6676',
    messagingSenderId: '554785606851',
    projectId: 'movie-app-d9b1d',
    storageBucket: 'movie-app-d9b1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACABvdH5qTPuMTWFSvYdY54X3uocksRjA',
    appId: '1:554785606851:ios:06b0b6ea35bf91b39d6676',
    messagingSenderId: '554785606851',
    projectId: 'movie-app-d9b1d',
    storageBucket: 'movie-app-d9b1d.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACABvdH5qTPuMTWFSvYdY54X3uocksRjA',
    appId: '1:554785606851:ios:06b0b6ea35bf91b39d6676',
    messagingSenderId: '554785606851',
    projectId: 'movie-app-d9b1d',
    storageBucket: 'movie-app-d9b1d.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjGVHy5QKMbkLMtmySwNfImbhMhlPDLWg',
    appId: '1:554785606851:web:d7e05a6925bed75d9d6676',
    messagingSenderId: '554785606851',
    projectId: 'movie-app-d9b1d',
    authDomain: 'movie-app-d9b1d.firebaseapp.com',
    storageBucket: 'movie-app-d9b1d.appspot.com',
    measurementId: 'G-XSR76C9ZME',
  );
}
